
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  adapter: postgresql
  database: timetracker_development
  encoding: unicode
  username: admin
  password: 1234
  host: localhost
  pool: 5 

test:
  <<: *default
  database: timetracker_test
  encoding: unicode
  username: admin
  password: 1234
  host: localhost
  pool: 5 


production:
  <<: *default
  database: timetracker_production
  username: timetracker
  password: <%= ENV['TIME_TRACKER_DATABASE_PASSWORD'] %>
  encoding: unicode
  pool: 5 